after :remedy do

Action.create(activity:"You can begin completing pre-op testing", number: 30, unit: "days", timeline: "before", remedy_id: 287)
Action.create(activity:"You must complete pre-op testing", number: 5, unit: "days", timeline: "before", remedy_id: 287)
Action.create(activity:"Pay bills by", number: 3, unit: "days", timeline: "before", remedy_id: 287)
Action.create(activity:"Schedule baby sitter by", number: 1, unit:"week", timeline:"before", remedy_id: 287)
Action.create(activity:"Schedule pet sitter by", number: 1, unit:"week", timeline:"before", remedy_id: 287)
Action.create(activity:"Complete meal prep", number: 1, unit:"day", timeline:"before", remedy_id: 287)
Action.create(activity:"Fill prescriptions", number: 1, unit:"week", timeline:"before", remedy_id: 287)
Action.create(activity:"Fasting by midnight", number: 1, unit:"day", timeline:"before", remedy_id: 287)
Action.create(activity:"Arrive at hospital 2 hours before surgery", number: 2, unit:"hours", timeline:"before", remedy_id: 287)
Action.create(activity:"If you are staying overnight, be sure to bring your necessary items with you", number: 3, unit:"hours", timeline:"before", remedy_id: 287)
Action.create(activity:"If you are leaving the hospital today, be sure to have someone to drive you home", number: 2, unit:"hours", timeline:"after", remedy_id: 287)
Action.create(activity:"Schedule follow-up appointment with doctor", number:1, unit:"week", timeline:"after", remedy_id: 287)
Action.create(activity:"Schedule 1st physical therapy", number: 1, unit:"month", timeline:"after", remedy_id: 287)
Action.create(activity:"You can begin completing pre-op testing", number: 30, unit: "days", timeline: "before", remedy_id: 23)
Action.create(activity:"You must complete pre-op testing", number: 5, unit: "days", timeline: "before", remedy_id: 23)
Action.create(activity:"Pay bills by", number: 3, unit: "days", timeline: "before", remedy_id: 23)
Action.create(activity:"Schedule baby sitter by", number: 1, unit:"week", timeline:"before", remedy_id: 23)
Action.create(activity:"Schedule pet sitter by", number: 1, unit:"week", timeline:"before", remedy_id: 23)
Action.create(activity:"Complete meal prep", number: 1, unit:"day", timeline:"before", remedy_id: 23)
Action.create(activity:"Fill prescriptions", number: 1, unit:"week", timeline:"before", remedy_id: 23)
Action.create(activity:"Fasting by midnight", number: 1, unit:"day", timeline:"before", remedy_id: 23)
Action.create(activity:"Arrive at hospital 2 hours before surgery", number: 2, unit:"hours", timeline:"before", remedy_id: 23)
Action.create(activity:"If you are staying overnight, be sure to bring your necessary items with you", number: 3, unit:"hours", timeline:"before", remedy_id: 23)
Action.create(activity:"If you are leaving the hospital today, be sure to have someone to drive you home", number: 2, unit:"hours", timeline:"after")
Action.create(activity:"Schedule follow-up appointment with doctor", number:1, unit:"week", timeline:"after", remedy_id: 23)
Action.create(activity:"Schedule 1st physical therapy", number: 1, unit:"month", timeline:"after", remedy_id: 23)
Action.create(activity:"Do not lift heavy objects for", number: 6, unit:"weeks or until instructed by Doctor", timeline:"after", remedy_id: 23)
Action.create(activity:"Remove dressings", number: 48, unit:"hours", timeline:"after", remedy_id: 23)
Action.create(activity:"No soaking in tub/swimming for", number: 2, unit:"weeks", timeline:"after", remedy_id: 23)
Action.create(activity:"It may be helpful to sleep in a recliner for", number: 1, unit:"week", timeline:"after", remedy_id: 23)
Action.create(activity:"Remove sling only to shower and to straighten elbow/wrist for", number:1, unit:"month", timeline:"after", remedy_id: 23)
Action.create(activity:"Change dressings as needed starting", number: 1, unit:"day", timeline:"after", remedy_id: 287)
Action.create(activity:"Ice knee frequently for", number: 3, unit:"days", timeline:"after", remedy_id: 287)
Action.create(activity:"Can shower", number: 3, unit:"days", timeline:"after", remedy_id: 287)
Action.create(activity:"When showering keep knee covered in plastic for", number: 1, unit:"week", timeline:"after", remedy_id: 287)
Action.create(activity:"No weight on leg for", number: 6, unit:"weeks", timeline:"after", remedy_id: 287)


  # Find the Remedy for these actions
  # r = Remedy.find_by(code: "<CODE HERE>")
  # r.actions.create(activity: "Pay Bills", number: 3, unit: "days", timeline: "before")

end
